### ISSUE TITLE
LuisGen or Dispatch: Error when LUIS file does not have "patternAnyEntities" property

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#1070]
## Tool
Name: LuisGen or Dispatch
Version: 2.0.2.0
OS: Windows

## Describe the bug
When running LuisGen against the luis .json file generated by Dispatch tool, the .json file is missing the patternAnyEntities property. This causes the following error:

```
Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 108
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 126
   at LUISGen.CSharp.Entities(Object app, Writer w) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 212
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 272
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 151
```

If I add the property manually, LuisGen succeeds

**Comment by tsuwandy** [comment]
Should be fixed with tomorrow's am build.
