### ISSUE TITLE
LuisGen Export raise an exception 

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/botbuilder-tools#1092]
## Tool
Name: LuisGen
Version: 2.0.2
OS: Windows 10 17763

## Describe the bug
When LUIS Model JSON file contains regex entity, LuisGen tool gives error :
```
Generating file test.cs that contains class Luis.test.

Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 108
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 125
   at LUISGen.CSharp.Entities(Object app, Writer w) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 212
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 272
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 151`
```

## To Reproduce
1. msbot get dispatch --bot [bot-file] --secret [xxx] | luis export version --stdin > dispatch.json
2. luisgen disptach.json -cs Dispatch -o "c:\temp"

## Expected behavior
A CS code file should be generated.

## Additional context
There seems to have a mismatch between what LUIS tool generat and what luisgen is expecting. Check Utils.cs line 124 is
```
WriteInstances(app.regex_entities, writeInstance);
```
the correct code should be:
```
WriteInstances(app.regexEntities, writeInstance);
```

[bug]

**Comment by cleemullins** [comment]
@sachabruttin Up for submitting a PR? :)

**Comment by tsuwandy** [comment]
This is fixed, there was a service error (LUIS server).  See comments on this PR: https://github.com/microsoft/botbuilder-tools/pull/1149
