### ISSUE TITLE
LuisGen  RuntimeBinderException: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botbuilder-tools#1107]
## Tool
Name: LuisGen
Version: 2.0.2
OS: Win 10x64
## Describe the bug

RuntimeBinderException on json file

## To Reproduce
1. "luis export version --appId xxx --versionId "0.1" --authoringKey xxxx > general.json" this i have run on the general Luis app created using enterprise template bot 
2.  luisgen general.json -cs general 

Which is giving me an error of 

Generating file general.cs that contains class Luis.general.

Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 108
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.Utils.WriteInstances(JObject obj, Action`1 writeInstance) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 125
   at LUISGen.CSharp.Entities(Object app, Writer w) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 212
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 272
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 151

**Comment by chrimc62** [comment]
I have been unable to repro this issue.  If it still happens for you after making sure you have the latest luisgen package could you share your general.json?

**Comment by chrimc62** [comment]
I found an original file and the issue was a missing property which the service has fixed.  The next version of LUISGen 2.1.1 will include a fix to make it more robust.  Thanks for bringing up the issue.
