### ISSUE TITLE
Dispatch fails to setup intents to child services mapping

### ISSUE THREAD

**Issue by EPinci** [Microsoft/botbuilder-tools#1118]
## Tool
Name: Dispatch
Version: 1.4.5
OS: Windows 10.0.18362.86

## Describe the bug
```dispatch create``` and ```dispatch refresh``` always throws this exception:
```
Failed setting up intents to child services mapping - System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Fuse.Core.Web.HttpClient.ProcessRequestAsync(Request request, Func`2 responseHandler)
   at Microsoft.Fuse.Core.Web.HttpClient.<>c__DisplayClass4_0.<<ProcessAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Fuse.Core.Web.WebClient.ProcessRobustAsync(Request request, Func`2 requestHandler)
   at Microsoft.Fuse.Core.Web.HttpClient.ProcessAsync(Request request)
   at Microsoft.Fuse.Core.AsyncEx.InvokeSync[T](Func`1 function)
   at Microsoft.Fuse.Dispatch.LuisApplicationManager.SetupDispatchIntentChildMapping()
   at Microsoft.Fuse.Dispatch.CreateLuisDispatchCommands.SetupDispatchIntentChildMapping()
Publishing bcbot model...
```
After the the command completes but then the bot get null references on the ```.ConnectedService``` property.

Note that I'm running against westeurope LUIS.

**Comment by EPinci** [comment]
For some unknown reasons, retraining and republishing the referenced bot (not the dispatch), fixed the thing...

**Comment by ayanez17** [comment]
I'm having the same issue. I've tried to retain and republish and that doesn't help.
