### ISSUE TITLE
Three MSLG tests failing

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-tools#1123]
See npm run coveralls task in build 135 at https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=57963&view=logs

 13 passing (29s)
  3 failing

  1) The mslg cli tool
       should output correctly
         should collate templates successfully:
     Error: ENOENT: no such file or directory, unlink '/Users/vsts/agent/2.150.3/work/1/s/packages/MSLG/finalResult_mslg.lg'
      at Object.unlinkSync (fs.js:951:3)
      at exec (test/mslg.cli.test.suite.js:118:24)
      at ChildProcess.exithandler (child_process.js:285:7)
      at maybeClose (internal/child_process.js:970:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Pipe._handle.close (net.js:597:12)

  2) The mslg cli tool
       should output correctly
         should collate templates from subfolder successfully:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at exec (test/mslg.cli.test.suite.js:131:28)
      at ChildProcess.exithandler (child_process.js:285:7)
      at maybeClose (internal/child_process.js:970:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Pipe._handle.close (net.js:597:12)

  3) The mslg cli tool
       should output correctly
         should write collated lg file to specific folder:
     Error: ENOENT: no such file or directory, unlink '/Users/vsts/agent/2.150.3/work/1/s/packages/MSLG/examples/validExamples/subValidExamples/finalResult_mslg.lg'
      at Object.unlinkSync (fs.js:951:3)
      at exec (test/mslg.cli.test.suite.js:143:24)
      at ChildProcess.exithandler (child_process.js:285:7)
      at maybeClose (internal/child_process.js:970:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Pipe._handle.close (net.js:597:12)

**Comment by feich-ms** [comment]
Fixed here https://github.com/microsoft/botbuilder-tools/pull/1133

**Comment by feich-ms** [comment]
The PR #1133 fixed the three tests failure issue, so I closed this issue.
