### ISSUE TITLE
JsonReaderException from dispatch create

### ISSUE THREAD

**Issue by arturl** [Microsoft/botbuilder-tools#123]
## Information:
* Tools Libraries: dispatcher
* Libraries' Versions: 
* OS: Windows

## Issue Description:
dispatcher throws an exception when I enter the same LUIS app twice

## Commands Example:

```bash

C:\test\botness>dispatch add -type luis -name TravelBooker -id d833c549-33f7-4c6c-9be0-1ebd41cc191d -key 97274b8102ac4c29830480182bd3f475
LUIS app id:d833c549-33f7-4c6c-9be0-1ebd41cc191d, name:TravelBooker, authoring key:97274b8102ac4c29830480182bd3f475, version:0.1 added to TravelD.dispatch

C:\test\botness>dispatch add -type luis -name TravelBooker -id c1e8e209-ea3c-44ba-a2e1-3ed7f4f60256 -key 97274b8102ac4c29830480182bd3f475
LUIS app id:c1e8e209-ea3c-44ba-a2e1-3ed7f4f60256, name:TravelBooker, authoring key:97274b8102ac4c29830480182bd3f475, version:0.1 added to TravelD.dispatch

C:\test\botness>dispatch create

```

## Expected Behavior:
Either success or error (note the name of the app TravelBooker in the second command is wrong)

## Actual Results:
```
Exporting services for dispatch...
Exporting TravelBooker LUIS application...
Exporting TravelBooker LUIS application...
Creating dispatch LUIS model json...
[2018-05-01T14:08:27][MergeAggregateLuisApplicationsOnPhraseLists,211,D:\a\1\s\AugmentLuisModel\UtilityLuisModelJsonAppManager.cs]The input LUIS App "C:\test\botness\data\_L_TravelBooker.json" cannot be validated, EXCEPTION=Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: ". Path '', line 70, position 6.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AugmentLuisModel.UtilityLuisModelJsonAppManager.MergeAggregateLuisApplicationsOnPhraseLists(JsonAppObject mergedLuisModelInJson, String luisModelInJsonTextAndOtherSourceSetting, ISet`1 nonInterchangeableFeatures, IList`1 interchangeableFeatureSets), luisModelInJsonString="{
  "luis_schema_version": "3.0.0",
  "versionId": "0.1",
  "name": "Spain",
  "desc": "Facts about Spain",
  "culture": "en-us",
  "intents": [
    {
      "name": "None"
    },
    {
      "name": "ShowCapital"
    },
    {
      "name": "ShowLocation"
    }
  ],
  "entities": [],
  "composites": [],
  "closedLists": [],
  "patternAnyEntities": [],
  "regex_entities": [],
  "prebuiltEntities": [],
  "model_features": [],
  "regex_features": [],
  "patterns": [],
  "utterances": [
    {
      "text": "the main city",
      "intent": "ShowCapital",
      "entities": []
    },
    {
      "text": "what is the capital",
      "intent": "ShowCapital",
      "entities": []
    },
    {
      "text": "where does the government sit",
      "intent": "ShowCapital",
      "entities": []
    },
    {
      "text": "where is andalusia",
      "intent": "ShowLocation",
      "entities": []
    },
    {
      "text": "where is barcelona",
      "intent": "ShowLocation",
      "entities": []
    },
    {
      "text": "where is basque country",
      "intent": "ShowLocation",
      "entities": []
    },
    {
      "text": "where is galicia",
      "intent": "ShowLocation",
      "entities": []
    },
    {
      "text": "where is prime minister",
      "intent": "ShowCapital",
      "entities": []
    }
  ]
}
      "intent": "OrderHotel",
      "entities": []
    }
  ]
}"

ERROR
Additional text encountered after finished reading JSON content: ". Path '', line 70, position 6.

------
CREATE
Usage: dispatch create [options]
Usage: dispatch create [.bot file]

Create/retrain and publish a LUIS application for dispatch

Options:

   -bot                    [Optional] Path to .bot file or bot services json file
   -dispatch               [Optional] Path to .dispatch file
   -hierarchical           [Optional] Default to true.  If false, existing intents from source LUIS model(s) will be available as the dispatch intents.    -dataFolder             [Optional] Working directory for the tool

```

**Comment by tsuwandy** [comment]
Fixed.  The second add will not be allowed to go through since app name is unique in LUIS (with the same authoring key)

**Comment by arturl** [comment]
:clap:
