### ISSUE TITLE
Unable to install dispatch tool on Ubuntu 18

### ISSUE THREAD

**Issue by sunilbinghamton** [microsoft/botbuilder-tools#1292]
Tools Libraries: botdispatch 
Linux - Ubuntu 18 LTS

While trying to install botdispatch npm module as a part of bot framework 4 on Ubuntu 18 installation stops with this error.

```bash
sudo npm install -g botdispatch
/usr/bin/dispatch -> /usr/lib/node_modules/botdispatch/bin/dispatch.js

> dotnet-2.1@2.1.1003 postinstall /usr/lib/node_modules/botdispatch/node_modules/dotnet-2.1
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.1@2.1.1003 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dotnet-2.1@2.1.1003 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by tsuwandy** [comment]
@sunilbinghamton, did you preinstall .NET Core runtime by following instructions on this page prior to running the npm install command?  
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x.

It's listed on readme as prerequisite for Linux installation.  Thanks!

**Comment by sunilbinghamton** [comment]
Yes. I have preinstalled .NET core runtime following the readme. 
Sorry, I should have mentioned this before.

**Comment by tsuwandy** [comment]
Thanks @sunilbinghamton.  Trying to get a repro.

**Comment by tsuwandy** [comment]
I wasn't able to install .NET Core 2.1 on my Linux VM but could you try following this workaround?  He installed dotnet-2.1 locally and it worked.

https://github.com/fearthecowboy/dotnet/issues/2

**Comment by sunilbinghamton** [comment]
Yes, the work around worked. Thanks a lot.
