### ISSUE TITLE
Using LUISGen with dispatch result fails

### ISSUE THREAD

**Issue by ThomasPe** [microsoft/botbuilder-tools#1320]
## Information:
* Tools Libraries: LUISGen, qnamaker, botdispatch
* Libraries' Versions: latest
* OS: Windows

## Issue Description:
I have a botframework v4 bot using dispatch to consolidate a LUIS app & a QnA Maker app.
When the request is being handeld by LUIS i'd like to convert the contents of the connectedServiceResult to my LUISGen generated class. However the Convert() method of my generated model fails as both entities & intents are arrays that fail to be converted to 
`public _Entities Entities;` and `public Dictionary<Intent, IntentScore> Intents;`
Am I missing here something?

## Reproduction Steps:
1. Create a Bot with Dispatch
2. Generate LUISGen model für LUIS App
3. Try to convert the result for this model (inside the connectedServiceResult of the dispatch result) to this LUISGen model

## Expected Behavior:
Should return object as LUISGen model type

## Actual Results:
JSONConvert crashes as intents & entities can't be mapped properly.

### LUISGen Model

```c#
// <auto-generated>
// Code generated by LUISGen ChatbotLUIS.json -cs Luis.ChatbotLUIS -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class ChatbotLUIS: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            canteen_menu, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] food;

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Lists
            public string[][] food_type;

            // Instance
            public class _Instance
            {
                public InstanceData[] datetime;
                public InstanceData[] food;
                public InstanceData[] food_type;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<ChatbotLUIS>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
```
### JSON Dispatch Result
```JSON
{
  "query": "was gibt es heute zu vegetarisches zu essen",
  "topScoringIntent": {
    "intent": "l_Chatbot",
    "score": 0.9581891
  },
  "intents": [
    {
      "intent": "l_Chatbot",
      "score": 0.9581891
    },
    {
      "intent": "q_itservicedesk",
      "score": 0.0518143177
    },
    {
      "intent": "None",
      "score": 0.00142146472
    }
  ],
  "entities": [],
  "connectedServiceResult": {
    "query": "was gibt es heute zu vegetarisches zu essen",
    "topScoringIntent": {
      "intent": "canteen_menu",
      "score": 0.995366156
    },
    "intents": [
      {
        "intent": "canteen_menu",
        "score": 0.995366156
      },
      {
        "intent": "None",
        "score": 0.00429999875
      }
    ],
    "entities": [
      {
        "entity": "heute",
        "type": "builtin.datetimeV2.date",
        "startIndex": 12,
        "endIndex": 16,
        "resolution": {
          "values": [
            {
              "timex": "2019-10-09",
              "type": "date",
              "value": "2019-10-09"
            }
          ]
        }
      },
      {
        "entity": "vegetarisches",
        "type": "food_type",
        "startIndex": 21,
        "endIndex": 33,
        "resolution": {
          "values": [
            "vegetarian"
          ]
        }
      }
    ]
  }
}
```

### Converting dispatch result
```#c
var dispatchResult = luisResult.ConnectedServiceResult;
var luisResult = new ChatbotLUIS();
luisResult.Convert(dispatchResult);
```

**Comment by dmvtech** [comment]
I'm looking into this. It will take me a bit of time to reproduce and troubleshoot. I'll update as I have results.

**Comment by dmvtech** [comment]
Did you happen to get a null reference when running luisgen?

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LUISGen.Utils.NormalizeName(Object name) in D:\a\1\s\packages\LUISGen\src\Utils.cs:line 15
   at LUISGen.CSharp.Intents(Object intents, Writer w) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 52
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.CSharp.Generate(String description, Object app, String className, String space, String outPath) in D:\a\1\s\packages\LUISGen\src\CSharp.cs:line 269
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 144
```

**Comment by congysu** [comment]
@dmvtech can you please kindly update, when you've a repo.  Thanks.

**Comment by dmvtech** [comment]
@ThomasPe Can you share the exception you are getting? I was able to get something to fail by making one of the intents to be named differently (_my assumption is that you did no renaming of intents, but can you confirm?)._ 

Other than that, I'm not sure. If you share the exception, that might help determine what is happening.

**Comment by dmvtech** [comment]
Hi @thomaspe Can you share the exception?

**Comment by CoHealer** [comment]
@ThomasPe do you still require assistance or shall we consider the issue resolved?

**Comment by dmvtech** [comment]
Closing due to no activity.
