### ISSUE TITLE
Error installing botdispatch

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/botbuilder-tools#1334]
## Tool
Name: botdispatch
Version: *2.0.2*
OS: *Win 10*

## Describe the bug
The installation instructions from the tutorial fail when attempting to install LUISgen.  It has not been consistent with some machines succeeding and others failing.
Tried installing the botdispatch package with "npm I -g botdispatch" and the error is generated.

## To Reproduce
1. Open command prompt
2. Run: "npm install -g botdispatch ludown luis-apis qnamaker luisgen@2.0."

## Expected behavior
Expect the tools / packages to be installed without an error

## Screenshots
C:\WINDOWS\system32>npm install -g botdispatch ludown luis-apis qnamaker luisgen@2.0.2
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> luisgen@2.0.2 uninstall C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\luisgen
> dotnet tool uninstall -g LUISGen
Tool 'luisgen' (version '2.2.0') was successfully uninstalled.
> luisgen@2.0.2 preinstall C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\luisgen
> node dotnetpreinstall.js
C:\Users\mmhopkin\AppData\Roaming\npm\dispatch -> C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\bin\dispatch.js
C:\Users\mmhopkin\AppData\Roaming\npm\ludown -> C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\ludown\bin\ludown
C:\Users\mmhopkin\AppData\Roaming\npm\luis -> C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\luis-apis\bin\luis.js
C:\Users\mmhopkin\AppData\Roaming\npm\qnamaker -> C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\qnamaker\bin\qnamaker.js
> luisgen@2.0.2 install C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\luisgen
> dotnet tool install -g LUISGen
You can invoke the tool using the following command: luisgen
Tool 'luisgen' (version '2.2.0') was successfully installed.
> dotnet-2.1@2.1.1003 postinstall C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
Unable to install/use dotnet framework.
C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\static-loader.js:1
"use strict";function isNode(path){return possibilities.indexOf(path)>-1}function cmdlineToArray(text,result=[],matcher=/[^\s"]+|"([^"]*)"/gi,count=0){text=text.replace(/\\"/g,"�");const match=matcher.exec(text);return match?cmdlineToArray(text,result,matcher,result.push(match[1]?match[1].replace(/\ufffe/g,'\\"'):match[0].replace(/\ufffe/g,'\\"'))):result}function indexAfterStartsWith(command,text){return command.startsWith(text)?text.length:-1}function startsWithNode(command){if('"'==command.charAt(0))for(const each of possibilities){const val=indexAfterStartsWith(command,`"${each}" `);if(val>-1)return val}else for(const each of possibilities){const val=indexAfterStartsWith(command,`${each} `);if(val>-1)return val}return-1}function getInsertedArgs(loadedFileSystems){return common_1.select(loadedFileSystems,(p,c)=>`--load-module=${c}`)}function getInsertedArgString(loadedFileSystems){return`${get
TypeError: volume[member].bind is not a function
    at patchFilesystem (C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\static-loader.js:1:4885)
    at C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\static-loader.js:1:4908
    at Object.global.staticloader.undo (C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\static-loader.js:1:2495)
    at process.exit (C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\static-loader.js:1:2647)
    at ChildProcess.<anonymous> (C:\Users\mmhopkin\AppData\Roaming\npm\node_modules\botdispatch\node_modules\dotnet-2.1\dist\app.js:38:33)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.1@2.1.1003 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dotnet-2.1@2.1.1003 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mmhopkin\AppData\Roaming\npm-cache\_logs\2019-10-28T18_19_43_636Z-debug.log
C:\WINDOWS\system32>

[bug]

**Comment by jwiley84** [comment]
By installing one by one, you've been able to verify it's botdispatch causing this?

**Comment by CoHealer** [comment]
@bradrlaw, do you still require assistance?

**Comment by compulim** [comment]
@bradrlaw we are closing this due to inactivity. If you are still hitting this issue, please open a new issue and reference this one. Thanks!

**Comment by edwardtsbaum** [comment]
I am having the same issue, my botdispatch will not work, please help me solve this issue.
![saveasDispatch](https://user-images.githubusercontent.com/44621130/71607305-2237aa80-2b46-11ea-917b-a6af47d78e3f.PNG)
