### ISSUE TITLE
Install fails for botdispatch and botskills 

### ISSUE THREAD

**Issue by srajanpm** [microsoft/botbuilder-tools#1438]
#### What project is affected?
microsoft/botframework-solutions

#### What language is this in?
npm

### What happens?
Install fails for botdispatch while executing these commands:

npm install -g botdispatch @microsoft/botframework-cli

npm install -g botskills@latest

#### What are the steps to reproduce this issue?

Environment: macOS Darwin 10.13 , npm: 6.14.4 and dotnet SDK 3.1.300
1. install VStudio for mac
2. clone https://github.com/microsoft/botframework-solutions as VStudio for mac doesn't support VSIX packages
3. install .net core sdk - installs the latest version 3.1.300
4. install npm
5. install powershellcore
6. npm install -g botdispatch @microsoft/botframework-cli

#### What were you expecting to happen?
successful installation of botdispatch followed by botskills 

#### Can you share any logs, error output, etc.?
npm install -g botdispatch @microsoft/botframework-cli

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/bf -> /usr/local/lib/node_modules/@microsoft/botframework-cli/bin/run
/usr/local/bin/dispatch -> /usr/local/lib/node_modules/botdispatch/bin/dispatch.js

> @microsoft/botframework-cli@4.9.0 postinstall /usr/local/lib/node_modules/@microsoft/botframework-cli
> node scripts/postinstall.js

Help us improve products by allowing Microsoft to collect anonymous command and flags usage: (Y/N): n
Telemetry will remain disabled
At any time you may enable collect anonymous command and flags usage by changing the configuration using command:
bf config:set:telemetry --enable

> dotnet-2.1@2.1.1005 postinstall /usr/local/lib/node_modules/botdispatch/node_modules/dotnet-2.1
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/local/bin/node',
  path: '/usr/local/bin/node',
  spawnargs: [
    '/usr/local/lib/node_modules/botdispatch/node_modules/dotnet-2.1/dist/static-loader.js',
    '--load-module=/usr/local/lib/node_modules/botdispatch/node_modules/dotnet-2.1/dist/static_modules.fs',
    '/node_modules/yarn/bin/yarn.js',
    'add',
    'dotnet-2.1-osx-x64',
    '--force',
    '--silent',
    '--no-lockfile',
    '--json'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.1@2.1.1005 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dotnet-2.1@2.1.1005 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by munozemilio** [comment]
@tsuwandy could you please take a look at this one?

**Comment by tsuwandy** [comment]
@srajanpm, you tried uninstalled dotnet 3.1 and retry the install?

**Comment by srajanpm** [comment]
@tsuwandy yes I uninstalled dotnet 3.1 and retried the dotnet-2.1 install.

**Comment by tsuwandy** [comment]
@srajanpm, did you check out these related issues (installing on MacOS) added by @Batta32 in earlier thread:

https://github.com/microsoft/botbuilder-tools/issues/862
https://github.com/microsoft/botbuilder-tools/issues/176

.NET Core install instructionfor MacOS:
https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?pivots=os-macos&tabs=netcore31

**Comment by srajanpm** [comment]
@tsuwandy 

I followed #862 and it looks like it helped but not sure. 

I tried installing dotnet 2.1 locally instead of globally, seems like dotnet2.1 is installed - i see the following message:

_+ dotnet-2.1@2.1.1005
added 1 package and audited 1 package in 1.098s_

and an error:

_> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

npm WARN saveError ENOENT: no such file or directory, open '/Users/srajan/package.json'_

And checking with "dotnet --list-sdks" returns nothing.

**Comment by tsuwandy** [comment]
#862 actually has quite different instructions.  Did you pre-install dotnet first (per the prerequisite instructions https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#prerequisite):

https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?pivots=os-macos&tabs=netcore31

**Comment by a-b-r-o-w-n** [comment]
Closing due to inactivity. Feel free to re-open this.
