### ISSUE TITLE
[Azure CLI] az bot delete - failed to delete Bot

### ISSUE THREAD

**Issue by nodeomega** [Microsoft/botbuilder-tools#151]
## Information:
* Tools Libraries: az bot CLI
* Libraries' Versions: AZ tools download link per Bugbash email.
* OS: Windows 10, Powershell

## Issue Description:
When attempting to delete the bot through the CLI, I received a very long error message and the bot failed to be deleted.

Creating and deleting channels such as email appeared to work fine.

## Commands Example:
*This assumes the subscription/resource group was set as a default*
PS C:\Users\(username)> az bot delete --name BOTNAME

## Reproduction Steps:
1. Enter the command to delete the bot via Azure tools CLI.

## Expected Behavior:
az tools CLI would complete the bot deletion, and then return to the Powershell prompt, likely without any status message (other successful completions returned to the prompt with no message).

## Actual Results:
Was handed this error in Powershell.  Copied/Pasted here as the error ran longer than my Powershell window, and also the error's red text on blue background is indiscernible.

PS C:\Users\v-jonru> az bot delete
az bot delete: error: the following arguments are required: --name/-n
usage: az bot delete [-h] [--verbose] [--debug]
                     [--output {json,jsonc,table,tsv}] [--query JMESPATH]
                     [--resource-group RESOURCE_GROUP_NAME] --name NAME
PS C:\Users\v-jonru> az bot delete --name v-jonru-nodebot-bugbash
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/0389857f-2464-451b-ac83-5f54d565b1a7/resourceGroups/v-jonru/providers/Microsoft.BotService/botServices/v-jonru-nodebot-bugbash/channels/DirectLineChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/0389857f-2464-451b-ac83-5f54d565b1a7/resourceGroups/v-jonru/providers/Microsoft.BotService/botServices/v-jonru-nodebot-bugbash/channels/DirectLineChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 205, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/0389857f-2464-451b-ac83-5f54d565b1a7/resourceGroups/v-jonru/providers/Microsoft.BotService/botServices/v-jonru-nodebot-bugbash/channels/DirectLineChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Users\v-jonru\.azure\cliextensions\botservice\azext_bot\custom.py", line 119, in delete_bot
    channel_name=channelName
  File "C:\Users\v-jonru\.azure\cliextensions\botservice\azext_bot\botservice\operations\channels_operations.py", line 250, in delete
    response = self._client.send(request, header_parameters, **operation_config)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 231, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 205, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/0389857f-2464-451b-ac83-5f54d565b1a7/resourceGroups/v-jonru/providers/Microsoft.BotService/botServices/v-jonru-nodebot-bugbash/channels/DirectLineChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))
PS C:\Users\v-jonru> az bot delete --name v-jonru-nodebot-bugbash

**Comment by swagatmishra2007** [comment]
issue should be fixed now
