### ISSUE TITLE
LuisCLI version 2.0.10 broken

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#389]
**Describe the bug**
Latest LuisCLI package from myget is broken on install.

**To Reproduce**
1. Run "npm i luis-apis" from myget feed
2. Run "luis --help"
4. See error: 
 ~~~~~~~~~~~
luis : module.js:549
At line:1 char:1
 luis --help
    + CategoryInfo          : NotSpecified: (module.js:549:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    throw err;
    ^
Error: Cannot find module '../lib/luisAuthoring'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lamil\AppData\Roaming\npm\node_modules\luis-apis\bin\luis:12:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

 ~~~~~~~~~~~

**Comment by vishwacsena** [comment]
@cleemullins - this is broken in MyGet.
