### ISSUE TITLE
Az bot fails on MacOS

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#614]
## Tool
Name: AZ bot
Version: 0.4.1
OS: MacOS

## Describe the bug
AZ bot does not work on MacOS

```bash
Vishwacs-MBP:51.cafe-bot vishwacsenakannan$ az extension list
[
  {
    "extensionType": "whl",
    "name": "botservice",
    "version": "0.4.1"
  }
]
Vishwacs-MBP:51.cafe-bot vishwacsenakannan$ az bot create -g cafe3 --name cafebottrialsample --kind webapp --location westus --insights-location "West US 2"  --version v4 --lang Node
No module named 'azure.mgmt.botservice'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vishwacsenakannan/.azure/cliextensions/botservice/azext_bot/custom.py", line 11, in <module>
    from azure.mgmt.botservice.models import Bot, BotProperties, Sku
ModuleNotFoundError: No module named 'azure.mgmt.botservice'

```

## To Reproduce
1. install az cli on mac
2. install the bot extension
3. try any az bot command

## Expected behavior
AZ bot commands work on Mac

[bug]

**Comment by vishwacsena** [comment]
Installing AZ via homebrew per the AZ CLI documentation fixes this issue. https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest
