### ISSUE TITLE
az bot publish fails using enterprise template due to CLI error

### ISSUE THREAD

**Issue by jonasnorlund** [Microsoft/botbuilder-tools#867]
## Tool
Name: Azure CLI
Version: 2.0.53 (bot extension 0.4.3)
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
OS: Win 10

## Describe the bug
Unable to publish bot service using az bot publish

## To Reproduce
I have followed the installation instructions for enterprise template bot
1. Installed latest CLI, NPM, LUISGen etc accoring to this link
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0

2. Ran the following with my parameters for YOUR_BOT_NAME, YOUR_AUTHORING_KEY, LOCALE_FOLDER, REGION
msbot clone services --name "YOUR_BOT_NAME" --luisAuthoringKey "YOUR_AUTHORING_KEY" --folder "DeploymentScripts\LOCALE_FOLDER" --location "REGION

3. It creates everything in azure and updates my local files and then generates this error

Command failed: az bot publish --resource-group MYBOTNAME-n MYBOTNAME --subscription xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxx -v v4 --proj-file "MYBOTNAME.csproj" WARNING: The behavior of this command has been altered by the following ex  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", l  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", l  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", l  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", l  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", l  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\__init__.py", line 442, TypeError: __init__() missing 1 required positional argument: 'logger'bot)py", line 86, in publish_app

4.  I tried to run the publish by itself after using " az bot publish -g MYBOTNAME -n MYBOTNAME --proj-file MYBOTNAME.csproj --version v4" then I got this:

__init__() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", line 388, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", line 381, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", line 357, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1r22ouqy\azure-cli-core\azure\cli\core\__init__.py", line 442, in default_command_handler
  File "C:\Users\jonorlu\.azure\cliextensions\botservice\azext_bot\custom.py", line 86, in publish_app
    kudu_client = KuduClient(cmd, resource_group_name, resource_name, bot)
TypeError: __init__() missing 1 required positional argument: 'logger'

## Expected behavior
A published bot in Azure

[bug]

**Comment by stevengum** [comment]
@jonasnorlund Thanks for reporting this, we're looking into this now.

**Comment by jonasnorlund** [comment]
FYI: Instead of publishing the bot using CLI I did it directly from within VS and it worked fine.

**Comment by stevengum** [comment]
Closing due to inactivity as this has been addressed with the latest public release of msbot, version [**4.3.2**](https://www.npmjs.com/package/msbot/v/4.3.2). This version of msbot does not use the botservice extension, so you are not required to call az extension add -n botservice. 

If you still run into this issue, please **@mention** me in this issue or open up a new issue.
