### ISSUE TITLE
CLI on Linux: luis train - can't encode character '\u2026'

### ISSUE THREAD

**Issue by dawwa** [Microsoft/botbuilder-tools#893]
## Tool
Name: LUIS
Version: *LTS*
OS: *Linux, Ubuntu 16.04*

## Describe the bug
We are seeing this error and hope to see if this is known and have workaround.
It runs properly on Windows.

> msbot get $domain --bot $botFilePath --secret $botFileSecret | **luis train** version --wait –stdin

2019-01-04 22:57:40.942600: Training Domain [general]
2019-01-04 22:57:43.352634: Model Type StatusId Status 
2019-01-04 22:57:43.352719: Cancel Intent Classifier 9 Queued 
2019-01-04 22:57:43.352733: Escalate Intent Classifier 9 Queued 
2019-01-04 22:57:43.352741: Goodbye Intent Classifier 9 Queued 
2019-01-04 22:57:43.352750: Greeting Intent Classifier 9 Queued 
2019-01-04 22:57:43.352757: Help Intent Classifier 9 Queued 
2019-01-04 22:57:43.352771: Logout Intent Classifier 9 Queued 
2019-01-04 22:57:43.352779: Next Intent Classifier 9 Queued 
2019-01-04 22:57:43.352786: None Intent Classifier 9 Queued 
2019-01-04 22:57:43.352793: Previous Intent Classifier 9 Queued 
2019-01-04 22:57:43.352801: Restart Intent Classifier 9 Queued 
2019-01-04 22:57:45.557312: Model Type StatusId Status 
Seed-2019-01-04 22:57:45.637157: Exception encountered
Seed-2019-01-04 22:57:45.637227: Error: 
Traceback (most recent call last):
File "seed.py", line 54, in main
exitcode = launchpackage(unarchivedpath)
File "seed.py", line 144, in launchpackage
printwithdate(stroutline)
File "seed.py", line 161, in printwithdate
print("{}: {}".format(datetime.datetime.utcnow(), statement), flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 101: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "seed.py", line 164, in 
sys.exit(main())
File "seed.py", line 60, in main
printwithprefix(sys.exc_info())
File "seed.py", line 158, in printwithprefix
print("{}-{}: {}".format(seed_prefix, datetime.datetime.utcnow(), statement), flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 194: ordinal not in range(128)

[bug]

**Comment by congysu** [comment]
Relates to/caused by external code seed.py's unicode encoding/dec handling logic.

**Comment by daveta** [comment]
Documenting for other people.  @congysu investigated and the luis tool is sending console control characters to perform overwrites on text (fancy output) and that is causing the problem.

https://github.com/Microsoft/botbuilder-tools/blob/master/packages/LUIS/bin/luis.js#L737

The workaround is to use "quiet" mode.
