### ISSUE TITLE
Unexpected Token error for MSBot

### ISSUE THREAD

**Issue by Jhanbury** [Microsoft/botbuilder-tools#894]
## Tool
Name: Msbot
Version: 4.3.2
OS:Windows 10

## Describe the bug
I have downloaded the tool however, every command i enter returns the following error message:

```
msbot : C:\Users\username\AppData\Roaming\npm\node_modules\msbot\bin\msbot.js:52
At line:1 char:1
+ msbot -h
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\username...bin\msbot.js:52:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

## To Reproduce
1. Install npm package using npm install -g msbot
2. run any command 
3. uninstall and reinstall
4. run command

## Expected behavior
the command should run as normal

## Additional context
I am trying to encrypt an existing bot file in VS2017
I have validated the json of both the appsettings.json and the bot file.

**Comment by Jhanbury** [comment]
Found the error.

Update Nodejs version. 😑 

Version 1.0.51 presented the update message while the newer versions just displayed the error messages.
