### ISSUE TITLE
botdispatch fails to install in docker container

### ISSUE THREAD

**Issue by seank-com** [Microsoft/botbuilder-tools#919]
## Tool
Name: Dispatch
Version: 1.2.2
OS: Debian 9 (stretch)

## Describe the bug

Trying to create a container for all the bot-tools because I hate littering all over my dev machine. 

The following Dockerfile fails to build:

```
FROM node:lts-stretch

WORKDIR /root

RUN apt-get update && apt-get install apt-transport-https
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
RUN wget -q https://packages.microsoft.com/config/debian/9/prod.list
RUN mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
RUN apt-get update && apt-get install -y dotnet-sdk-2.2
RUN dotnet tool install -g LUISGen
RUN npm install -g yo generator-botbuilder chatdown msbot ludown luis-apis qnamaker botdispatch
```

With the following error

```bash
> dotnet-2.1@2.1.0 postinstall /usr/local/lib/node_modules/botdispatch/node_modules/dotnet-2.1
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/node EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.1@2.1.0 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dotnet-2.1@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-28T15_46_08_508Z-debug.log
```

I've tried installing dotnet-sdk-2.0, dotnet-sdk-2.1 & dotnet-sdk-2.2 all with the same result.

Thoe only work around I have found is to replace the last line of the Dockerfile with the following lines:

```
RUN npm install -g yo generator-botbuilder chatdown msbot ludown luis-apis qnamaker
RUN npm install -g --ignore-scripts botdispatch
WORKDIR /usr/local/lib/node_modules/botdispatch/node_modules/dotnet-2.1/
RUN node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
WORKDIR /root
```

This does not report any error and the dispatch command seems to work in the container.

## To Reproduce
1. Place the Dockerfile above in a file named ```Dockerfile``` in an empty folder
2. from a console window in that folder, run the following command
```bash
$ docker build -t bot-tools .
```

## Expected behavior

The docker command above builds the container without errors.

## Additional context

```bash
$ docker --version
Docker version 18.09.1, build 4c52b90
```

[bug]

**Comment by daveta** [comment]
Hi @seank-com : As a workaround, can you modify your Dockerfile to not install globally:
```
RUN npm install dotnet-2.1
RUN npm install botdispatch
```
Appears to be a [known thing with dotnet](https://github.com/fearthecowboy/dotnet/issues/2).  
Thanks.

**Comment by tsuwandy** [comment]
@daveta tested this and it worked for him.  We'll close this and let us know if you are still running into the same issue after following Dave's instruction.  Thanks!

**Comment by sgellock** [comment]
@Kaiqb you should consider if it's helpful to document this.  we could add it to the tools readme as an option
