### ISSUE TITLE
bugbash - az bot create throws on first run

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#978]
## Tool
Name: Az Bot
Version: 2.0.58
OS: *Win 10*

## Describe the bug
Ran the following command and got exception 

PS C:\temp> az bot create --kind webapp --name bagbush02202019-testbot --location westus --version v4 --verbose --resource-group bagbysg02202019
Microsoft application id not passed as a parameter. Provisioning a new Microsoft application.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FUQ9WTJMA to authenticate.
Unexpected polling state invalid_grant
Traceback (most recent call last):
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\six\six.py", line 693, in reraise
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\__init__.py", line 449, in default_command_handler
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\custom.py", line 90, in create
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\converged_app.py", line 20, in provision
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\adal_authenticator.py", line 41, in acquire_token
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 299, in acquire_token_with_device_code
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 128, in _acquire_token
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 292, in token_func
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\token_request.py", line 397, in get_token_with_device_code
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\oauth2_client.py", line 362, in get_token_with_polling
adal.adal_error.AdalError: Unexpected polling state invalid_grant
P.

## To Reproduce
see above

## Expected behavior
Ran the same command second time and was able to create the bot.

## Additional context
Ran the same command second time and was able to create the bot.

[bug]

**Comment by stevengum** [comment]
We're going to require that users pass in the App ID and App Secret, so this bug will not occur in the //BUILD release.

Closing as wontfix.
