### ISSUE TITLE
bugbash - az bot create fails

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/botbuilder-tools#986]
## Tool
Name: AZ CLI (bug bash build)
Version: *2.0.58*
OS: *Windows 10*

## az bot create fails when using MVC bot
Use the MVC Test Bot that has no .bot file. 

## To Reproduce
1. Run this command:
_C:\testdeployment\MVCTestBot>az bot create --kind webapp --name "MVCTestBot-KI" --location westus --version v4 --lang Csharp --verbose --resource-group azbotrg_
You get this error:
Configured default 'azclibotresourcegroup' for arg resource_group_name
Microsoft application id not passed as a parameter. Provisioning a new Microsoft application.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FLE3 to authenticate.
Unexpected polling state invalid_grant
Traceback (most recent call last):
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\six\six.py", line 693, in reraise
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-core\azure\cli\core\__init__.py", line 449, in default_command_handler
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\custom.py", line 90, in create
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\converged_app.py", line 20, in provision
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\azure-cli-botservice\azure\cli\command_modules\botservice\adal_authenticator.py", line 41, in acquire_token
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 299, in acquire_token_with_device_code
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 128, in _acquire_token
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\authentication_context.py", line 292, in token_func
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\token_request.py", line 397, in get_token_with_device_code
  File "C:\Users\stgum\AppData\Local\Temp\pip-install-chf26f0z\adal\adal\oauth2_client.py", line 362, in get_token_with_polling
adal.adal_error.AdalError: Unexpected polling state invalid_grant

## Expected behavior
A bot should be created in ABS.

[bug]

**Comment by Kaiqb** [comment]
This is a duplicate of [issue# 978](https://github.com/Microsoft/botbuilder-tools/issues/978).
